language: python
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
    - pip install -r requirements.txt

script:
#test patient_diagnosis_biosource_biomaterial_export tranformations
    - python -m unittest tests/test_table_transformations.py
