version: "3"
services:
    redis:
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        volumes:
            - redis-data:/data
    webapp:
        build:
            context: .
            dockerfile: ./Dockerfile
        command: ['python', '-m', 'packer']
        ports:
            - 8999:8999
        depends_on:
            - redis
        links:
            - redis
        environment:
          TRANSMART_URL: 'http://localhost:8081'
          KEYCLOAK_URL: 'http://localhost:8080/auth/realms/dev'
          CLIENT_ORIGIN_URL: 'http://localhost:4200'

    worker:
        build:
            context: .
            dockerfile: ./Dockerfile
        command:  ['celery', '-A', 'packer.tasks', 'worker', '-c', '4', '--loglevel', 'info']
        depends_on:
            - redis
        links:
            - redis

volumes:
  redis-data:
