version: "3"
services:
    redis:
        image: redis:alpine
        command: ["redis-server", "--appendonly", "yes"]
        hostname: redis
        volumes:
            - redis-data:/data
    webapp:
        image: thehyve/transmart-packer
        command: ['python', '-m', 'packer']
        ports:
            - 8999:8999
        depends_on:
            - redis
        links:
            - redis
        environment:
          TRANSMART_URL: 'https://transmart-dev.thehyve.net'
          KEYCLOAK_SERVER_URL: 'https://keycloak-dwh-test.thehyve.net'
          KEYCLOAK_REALM: 'transmart-dev'
          KEYCLOAK_CLIENT_ID: 'transmart-client'
          CLIENT_ORIGIN_URL: '*'

    worker:
        image: thehyve/transmart-packer
        command:  ['celery', '-A', 'packer.tasks', 'worker', '-c', '4', '--loglevel', 'info']
        depends_on:
            - redis
        links:
            - redis
        environment:
          TRANSMART_URL: 'https://transmart-dev.thehyve.net'

volumes:
  redis-data:
